//data reducers
export const SET_CLIENTS = "SET_CLIENTS";
export const SET_CLIENT = "SET_CLIENT";
export const SET_REVIEW = "SET_REVIEW";
export const SET_AVAILABLE_TRIPS = "SET_AVAILABLE_TRIPS";
export const SET_AVAILABLE_FUTURE_TRIPS = "SET_AVAILABLE_FUTURE_TRIPS";
export const SET_AVAILABLE_TRIP = "SET_AVAILABLE_TRIP";
export const LOADING_DATA = "LOADING_DATA";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_BOOKING_SUCCESS = "ADD_BOOKING_SUCCESS";
export const UPDATE_TICKETSCOUNT_SUCCESS = "UPDATE_TICKETSCOUNT_SUCCESS";
export const UPDATE_SEAT_SUCCESS = "UPDATE_SEAT_SUCCESS";
export const ADD_CART_FAIL = "ADD_CART_FAIL";
export const SET_CART = "SET_CART";
export const DELETE_TRIP_CART = "DELETE_TRIP_CART";
export const SET_BOOKINGS = "SET_BOOKINGS";
export const SET_BOOKING = "SET_BOOKING";
export const EDIT_STATUS = "EDIT_STATUS";
export const COMPANY_CREATE_REVIEW = "COMPANY_CREATE_REVIEW";
export const COMPANY_CREATE_COMPLAINT = "COMPANY_CREATE_COMPLAINT";

//UI reducers
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SERVER_ERROR = "SERVER_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const SET_ERROR = "SET_ERROR";
export const SET_ERRORS_SIGNUP_COMPANY = "SET_ERRORS_SIGNUP_COMPANY";
export const SET_ERROR_TRIP = "SET_ERROR_TRIP";
export const SET_ERROR_PAYMENTACCOUNT = "SET_ERROR_PAYMENTACCOUNT";

//user reducers
export const LOADING_USER = "LOADING_USER";
export const SET_USER = "SET_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const ADD_TRIP = "ADD_TRIP";
export const DELETE_TRIP = "DELETE_TRIP";
export const EDIT_TRIP = "EDIT_TRIP";

export const SET_PAYMENTACCOUNTS = "SET_PAYMENTACCOUNTS";
export const SET_PAYMENTACCOUNT = "SET_PAYMENTACCOUNT";
